### ISSUE TITLE
Bug: Decimal Precision only work's for 0 or 1

### ISSUE THREAD

**Issue by Leon3011** [nxt3AT/sankeydiagram.net#28]
```
in [100.12] total in
total in [20.55] out
```
If i set Decimal precision in the settings to 0 or 1 everything works as it should. But if i want to show the whole value without rounding - 2 decimals - nothing happens:
![image](https://user-images.githubusercontent.com/73185170/145952078-8a08fc89-c1e3-4364-90f5-1b3b87d92253.png)

**Comment by k4ds3** [comment]
confirmed. will release a fix soon
