### ISSUE TITLE
feature request: export/import sankeydiagram input as text file

### ISSUE THREAD

**Issue by k4ds3** [nxt3AT/sankeydiagram.net#31]
It would be nice if we had the possibility to export and import the sankey diagram input as a text file.

**Comment by domvo** [comment]
Craeted a PR:
https://github.com/nxt3AT/sankeydiagram.net/pull/33

**Comment by k4ds3** [comment]
Implemented by @domvo in PR #33 will be included in the next release (today||tomorrow)! ❤
