### ISSUE TITLE
Feature request: specify vertical ordering

### ISSUE THREAD

**Issue by brahn** [nxt3AT/sankeydiagram.net#64]
**UPDATE: I found the "sort nodes by line number" setting, and with a bit of input hackery I was able to get it to work.  See comment for solution**

----

Is there a way to specify the vertical ordering of the nodes?  Apologies if I'm overlooking it in the documentation.

As a concrete example -- using the input included at the bottom of this comment produced the following diagram.  I would like to tweak the ordering so that X1 and X2 are always at the top.

<img width="1075" alt="Monosnap SankeyDiagram Tool: Generate Sankey Diagrams with ease 2024-10-29 08-40-24" src="https://github.com/user-attachments/assets/8f1f3cdf-b90a-45c6-a1d7-8bfbf619967e">

The use case here is that I have a population of agents that can be in states A, B, or C. At regular intervals I record each agent's state and would like to see how they move between states.  However, I also have agents joining the population (represented by X) and I'd like them to consistently appear as coming from the top of the diagram, rather than the middle.  And though this example doesn't have it, I could imagine having agents leaving the population and I'd like to see that "exit" process" as going to a set of states at the bottom of the diagram

Thanks!

```
A1 [50] A2
A1 [50] B2  
B1 [50] B2
B1 [50] C2
C1 [100] C2
X1 [20] A2
X1 [20] B2
X1 [20] C2

A2 [30] A3
A2 [40] B3  
B2 [60] B3
B2 [60] C3
C2 [170] C3
X2 [20] A3
X2 [20] B3
X2 [20] C3
```

**Comment by brahn** [comment]
Solution: 
1. Under settings, check the "sort nodes by line number" box
2. Include some "fake" lines to name all the top nodes at the start of the input:


```
// Force X1, X2 to the top

X1 [0] X2

// Rest of data with no ordering as desired

X1 [20] A2
X1 [20] B2
X1 [20] C2
X2 [20] A3
X2 [20] B3
X2 [20] C3


A1 [50] A2
A1 [50] B2  
B1 [50] B2
B1 [50] C2
C1 [100] C2

A2 [30] A3
A2 [40] B3  
B2 [60] B3
B2 [60] C3
C2 [170] C3
```

**Comment by JonasDoesThings** [comment]
@brahn First of all: thx for the great & detailed / reproducible issue description :)

Great that you found a workaround, I should definitely look into optimising the parsing-logic, so the dummy-lines are not required! 

btw, would you prefer the "sort by line number" setting to be the default option? 
I have to make up my mind regarding that, or find a way to make it more prominent / clear, you are already the second person who asked me if that is possible, so maybe I could find a way to improve the visibility of this setting (or change the default)

Greetings from Austria and have a nice evening!

**Comment by brahn** [comment]
Hi @JonasDoesThings thanks for the follow-up! 

In answer to your question:
> would you prefer the "sort by line number" setting to be the default option [...] or find a way to make it more prominent / clear

I think making it more prominent/clear is the most important thing; whether or not it's on by default should depend on what most users want/expect.
